### ISSUE TITLE
Using SerialPortStream library with XModemProtocol

### ISSUE THREAD

**Issue by L0uisc** [emancipatedMind/XmodemProtocol#7]
Is it possible to use [SerialPortStream](https://www.nuget.org/packages/SerialPortStream/) instead of SerialPort with this library? Or maybe let the Port property be of type IPort, which implements some interface and provide the System.IO.Ports.SerialPort wrapper out of the box to enable me to wrap SerialPortStream myself?

**Comment by emancipatedMind** [comment]
So, check out the XModemProtocol.Communication.ICommunicator interface. The
XModemCommunicator actually uses this interface to perform its reading, and writing operations.

 Implement it in your own way with the SerialPortStream, and pass the class
to the constructor which accepts the interface.

The Port property was a vestige of the past not eliminated due to backwards
compatibility.

Thanks.

**Comment by L0uisc** [comment]
Thanks! Will look into it.
